### ISSUE TITLE
Why using classic format?

### ISSUE THREAD

**Issue by Powersource** [ssb-ngi-pointer/ssb-secure-partial-replication#17]
This is my hunch, correct me if I'm wrong:

1. We only want index feeds to point at the old main feed, since newer feeds can be partially replicated through metafeeds and tangles
2. The main feed is classic format, so the index is only useful to you if you're able to read the main feed also

**Comment by Powersource** [comment]
@arj03

**Comment by arj03** [comment]
Correct 🙂
